export * from 'components/App/App';
export * from 'components/Header/Header';
export * from 'components/Container/Container.styled';
export * from 'components/MovieDetail/MovieDetail.styled';
export * from 'components/Grid/Grid.styled';
export * from 'components/Loader/Loader';
export * from 'components/Trendings/Trendings';
export * from 'components/Reviews/Reviews';
export * from 'components/Cast/Cast'
export * from 'components/SearchForm/SearchForm'